// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-redesign/MedicalClean.tsx": () => import("../components/mockups/dashboard-redesign/MedicalClean.tsx"),
  "./components/mockups/dashboard-redesign/ModernGlass.tsx": () => import("../components/mockups/dashboard-redesign/ModernGlass.tsx"),
  "./components/mockups/dashboard-redesign/PremiumDark.tsx": () => import("../components/mockups/dashboard-redesign/PremiumDark.tsx")
};
